### ISSUE TITLE
Skip dashes

### ISSUE THREAD

**Issue by andreif** [danielwhatmuff/gh#1]
Is there a good reason for using dashes? Using them feels more like options not targets. 
Why not this way:
```
gh p
gh pulls
```
Autocompletion should not be a problem in both cases, right?

**Comment by andreif** [comment]
Also, if autocompletion works, then it should not provide shorter targets then, only the full versions to make more sense.

**Comment by danielwhatmuff** [comment]
Good point and nope not a _good_ reason. Want to PR a find and replace on '-' and we can test?

**Comment by andreif** [comment]
I won't have time for it, sorry. I was/am considering adding other functions working on which is now stale also...
